import { defineConfig } from 'astro/config';
import react from '@astrojs/react';

// The service worker and web app manifest live in `public/` and are owned by the
// build (Astro copies them verbatim). They used to be generated by
// vite-plugin-pwa, but that plugin does not emit `sw.js` under Astro — the
// deployed app 404'd on /sw.js, which made the app non-installable and blocked
// web push.
export default defineConfig({
  output: 'static',
  integrations: [react()],
  vite: {
    server: {
      // Proxy /api to the backend during dev (avoids CORS).
      // The backend routes have NO /api prefix, so it is stripped here.
      proxy: {
        '/api': {
          target: 'http://localhost:5000',
          changeOrigin: true,
          rewrite: (p) => p.replace(/^\/api/, ''),
        },
      },
    },
  },
  server: {
    host: true,
    port: 4321,
  },
});